### PR TITLE
Added links to navbar

### PR DESCRIPTION
**Pull request by Nopraz**
The links were missing on the navbar, they were only present in the sidebar.

### CODE REVIEW

**Comment by carlzoo** [comment]
https://github.com/carlzoo/scalperr-ui/issues/27

**Comment by carlzoo** [comment]
Hi @Nopraz Thanks for your interest in the project. If you are on discord send me your username I will give you collaborator access so you don't need to fork the repo in the future.

**Review by carlzoo — APPROVED** [review]

**Comment by Nopraz** [comment]
> Hi @Nopraz Thanks for your interest in the project. If you are on discord send me your username I will give you collaborator access so you don't need to fork the repo in the future.

Sure ! There it is : Nopraz#4242

**Comment by carlzoo** [comment]
sent you a request on discord and github, this is good to merge

**Pull request merged**
